#include <iostream>
using namespace std;
int main()
{
  cout << "#ifndef ALPHA_HELP_STRING_H_" << endl;
  cout << "#define ALPHA_HELP_STRING_H_" << endl;
  cout << "/* file auto-generated by gen-help-string.cpp */" << endl;
  cout << "#include <string>" << endl;
  cout << "using namespace std;" << endl;
  cout << "string help_string=\"";
  while(cin)
    {
      char c=cin.get();
      if(c=='\n')
	{
	  cout << "\\n";
	}
      else if(!cin.eof())
	cout << c;
    }
  cout << "\";" << endl;
  cout << "#endif";
}
